/* nodes-details.js — NODE_DETAILS for tab_nodes tooltip data */

const NODE_DETAILS = {
  spec:    { role:'SPEC v1.0 \u00b7 Governing Architecture', status:'LOADED', sc:'#9f00fa',
    m:[['Sections','36 total \u00b7 Full spec'],['Key changes','Ephemeral workers \u00b7 Streaming STT/TTS \u00b7 VAD \u00b7 Pre-render \u00b7 Barge-in'],['Scope','Sales AI product + PS client config'],['Status','Active \u00b7 April 2026']],
    note:'v1.9: ephemeral template-based workers (RunPod US-CA-2), Parakeet RNNT streaming, Silero VAD, pre-rendered first turn, barge-in, comfort noise, dual-channel call recording.' },
  intel:   { role:'ZC_COMMUNICATION_INTEL \u00b7 Call Intelligence', status:'INDEXED', sc:'#d36eff',
    m:[['Deals analyzed','110 real HubSpot deals'],['Win rate post-30d','34.5% (from data analysis)'],['Best opener','Proposal# + property name \u2014 never generic'],['DNC signal','Hostile tone \u2192 immediate drop + DNC flag'],['Key insight','Last client action matters more than calendar age']],
    note:'110 real deals analyzed for call patterns. This data drives script tier selection and opener strategy. T1 (email history signal) always beats T2 (staleness bucket).' },
  ranking: { role:'Queue Ranking Engine \u00b7 Priority Algorithm', status:'RUNNING', sc:'#ee9612',
    m:[['Eligibility','status=sent + \u22657d stale + not deleted'],['Exclusions','clientID\u226062 \u00b7 blacklists loaded'],['VIP flag','$200k+ \u2192 Alex review'],['DNC','Unsubscribed opt_in_status \u2192 skip'],['Sort','Value \u00d7 staleness \u00d7 rep weight']],
    note:'Nothing gets dialed without passing every check here. Morgan\'s deals (propIDs 10572, 10433, 10835, 8793) are always excluded.' },
  zc_data: { role:'Schema + SQL \u00b7 Data Model Reference', status:'LOADED', sc:'#60be35',
    m:[['Files','ZC_DATA_MODEL.md \u00b7 ZC_SQL_QUERIES.md'],['Key rule','Always query via entity_1.* views'],['Gotcha','_proposal has no clientID \u2014 join via _location'],['Contacts','Tier 1/5/6 resolution only'],['Warning','_location contact fields are NULL in prod']],
    note:'Canonical SQL queries for eligibility, contact resolution, grouping. Never use th_db_live.* directly.' },
  alex:    { role:'Operator \u00b7 Human-in-the-loop', status:'ONLINE', sc:'#60be35',
    m:[['Last action','Batch #12 pending approval'],['Interface','Sales Controller + Matrix'],['Override','Any call \u00b7 any time'],['Phone','(555) 267-7573 (fallback)']],
    note:'Alex approves every batch before it fires. Nothing dials without the green "Go" button.' },
  matrix:  { role:'Intel Hub \u00b7 C&C \u00b7 Sales Communication', status:'CONNECTED', sc:'#60be35',
    m:[['Uptime','2d 14h'],['Last heartbeat','4s ago'],['Channels','#queue #transfers #won #errors #morgan'],['Protocol','Matrix IM \u00b7 End-to-end encrypted'],['Users','Alex (full control) \u00b7 Sales reps (read-only) \u00b7 SalesClaw bot \u00b7 Morgan (Q&A only)'],['Reps see','#transfers and #won only \u2014 read-only']],
    note:'Alex sends commands via Matrix, reps get read-only transfer alerts (#transfers) and win notifications (#won). Morgan gets financial Q&A in #morgan with weekly Friday auto-summary. SalesClaw posts batch updates to #queue. All failures to #errors (Alex only).' },
  claw:    { role:'SalesClaw \u00b7 Rust Daemon (ZeroClaw fork)', status:'RUNNING', sc:'#60be35',
    m:[['Language','Rust \u00b7 Autonomous daemon'],['Base','Fork of zeroclaw-labs/zeroclaw'],['PID','47821'],['Heartbeat','Every 4s'],['Queue pending','24 calls \u00b7 Batch #12'],['Next check','58s']],
    note:'Fork of ZeroClaw \u2014 stripped and customized for Sales AI. SOUL.md/HEARTBEAT.md workspace conventions preserved. Not tracking upstream. Never touches live calls directly.' },
  pt:      { role:'FieldTECH \u00b7 Source of Truth', status:'SSH \u25c8', sc:'#60be35',
    m:[['Access','SSH tunnel \u00b7 port 3307'],['Views','entity_1.* (entityID=1)'],['Proposals','1,357 stale \u00b7 $37.5M'],['Contacts','Tier 1 / 5 / 6 resolution'],['Warning','Never use th_db_live.* directly']],
    note:'_location contact fields are all NULL in production. Use HubSpot for phone/email fallback.' },
  postmark:{ role:'Email Delivery \u00b7 Postmark', status:'READY', sc:'#ee9612',
    m:[['Provider','Postmark \u2014 dedicated transactional infra'],['From','phil.s@pinnacleservices.demo'],['Domain','pinnacleservices.demo (SPF/DKIM/DMARC)'],['Sequence touches','Day 14 \u00b7 Day 44 (final)'],['Cost','~$15/mo'],['Template','SCRIPTS_EMAIL.md']],
    note:'Postmark \u2014 best-in-class inbox placement, no shared IP pool risk. Sends from phil.s@pinnacleservices.demo.' },
  hs:      { role:'HubSpot \u00b7 CRM Mirror', status:'OK \u00b7 4m', sc:'#60be35',
    m:[['App ID','00000000 (Sales AI OAuth)'],['Token expires','23h 14m'],['Last sync','4 min ago'],['Deals','1,322 with HS deal ID'],['Owner match','By hs_owner_id \u2014 NOT by email']],
    note:'Do NOT use _hs_access_token table \u2014 that\'s TripTECH\'s app. 3 confirmed email mismatches.' },
  pg:      { role:'PostgreSQL \u00b7 Internal DB', status:'OK', sc:'#60be35',
    m:[['DB name','phil-internal'],['call_log','47 rows'],['sequences','12 active'],['attribution','6 pending \u00b7 source of truth'],['Host','sales-app (localhost)']],
    note:'FieldTECH CSM dashboard is broken \u2014 this DB is the real attribution source of truth.' },
  kb:      { role:'Knowledge Base \u00b7 Preheat Context', status:'LOADED', sc:'#60be35',
    m:[['Core','SPEC v1.0 (\u00a71\u201336)'],['Includes','ZC_DATA_MODEL \u00b7 ZC_SQL_QUERIES'],['Includes','ZC_CONTACTS \u00b7 ZC_HUBSPOT \u00b7 ZC_DECISIONS'],['Approx tokens','~45k per call load'],['Preheat time','~2s before each call']],
    note:'Entire spec loaded into Claude\'s context window before each call. ZC_COMMUNICATION_INTEL informs script tier selection separately.' },
  scripts: { role:'Script Library \u00b7 12 Tier Variants', status:'READY', sc:'#60be35',
    m:[['Main tiers','T1-A/B/C/D \u00b7 T2-A/B/C \u00b7 T3-A/B (9 variants)'],['Override tiers','T4-A/C/D (enforcement, departed rep, resurrection)'],['Selection','First match wins: P1 overrides \u2192 P2 recency \u2192 P3 email \u2192 P4 staleness'],['Also','SMS \u00b7 Voicemail \u00b7 Email scripts'],['Intel feeds','ZC_COMMUNICATION_INTEL \u2192 tier selection']],
    note:'T1 (email history signal) always beats T2 (staleness bucket). Last client action matters more than the calendar. 12 total tier variants across 4 priority levels \u2014 no T4-B exists.' },
  backend: { role:'Sales Backend \u00b7 Rust (Axum)', status:'STANDBY', sc:'#ee9612',
    m:[['Language','Rust \u00b7 Axum web framework'],['Uptime','2d 14h'],['Memory','1.2 GB / 2 GB'],['Last call','propID #7856 \u00b7 Michelle Forkas'],['Role','Pre/post call only \u00b7 Idle during live calls'],['Host','sales-app (2GB CPU \u00b7 ~$12/mo)']],
    note:'Rust/Axum backend. Idle during live calls \u2014 Worker owns the voice pipeline and all Telnyx call control. Backend handles attribution, HubSpot/FieldTECH sync, phone normalization, worker lifecycle coordination. No Python on sales-app.' },
  gpu:     { role:'Sales Worker \u00b7 Ephemeral GPU \u00b7 RunPod Template', status:'OFFLINE', sc:'#b0b0b0',
    m:[['GPU','RTX 4000 Ada (benchmark-dependent)'],['VRAM','20 GB'],['Cost','$0.26/hr on-demand'],['Lifecycle','booting \u2192 ready \u2192 armed \u2192 in_call \u2192 idle \u2192 dead'],['Boot-to-armed','<4 min from RunPod template (target <2.5 min)'],['Contains','Pipecat + RNNT + Silero VAD + SmartTurn v3'],['Health check','STT/LLM/TTS latency tested before first call']],
    note:'Ephemeral template-based workers (RunPod US-CA-2). Created per-batch, destroyed after. Models pre-loaded on disk. Secrets injected via env vars at boot \u2014 never baked into image.' },
  vad:     { role:'Silero VAD \u00b7 Voice Activity Detection', status:'OFFLINE', sc:'#b0b0b0',
    m:[['Model','Silero VAD'],['Threshold','200ms stop_secs (configurable)'],['Location','Sales Worker GPU'],['Overlap','Runs concurrently with Parakeet RNNT'],['Barge-in','500ms client speech \u2192 interrupt Sales']],
    note:'VAD and RNNT stream concurrently \u2014 ~90% of transcript complete by VAD silence trigger. Barge-in: >500ms client speech interrupts Sales; <500ms ignored as backchannel.' },
  parakeet:{ role:'Parakeet RNNT 1.1B \u00b7 Streaming STT', status:'OFFLINE', sc:'#b0b0b0',
    m:[['Model','Parakeet RNNT 1.1B (NVIDIA)'],['Mode','Streaming \u2014 incremental transcription'],['Marginal latency','~0ms after VAD trigger'],['Host','Sales Worker (ephemeral)'],['Benchmark','Must test on 8kHz G.711 \u03bc-law audio'],['Fallback','Moonshine \u2014 if RNNT underperforms on phone audio'],['Controller','STT Model toggle (manual only, never auto-switches)']],
    note:'Streaming RNNT replaces offline TDT. Near-zero marginal latency because transcription overlaps with audio input \u2014 ~90% of transcript complete by VAD silence trigger. If RNNT accuracy drops on 8kHz G.711 phone audio \u2192 evaluate Moonshine replacement.' },
  sonnet:  { role:'Claude Sonnet 4.6 \u00b7 Live Call LLM', status:'PREHEATED', sc:'#60be35',
    m:[['Model','claude-sonnet-4-6'],['Host','Anthropic API (cloud)'],['Context','200k tokens'],['Usage','Live call ONLY \u2014 never async'],['Preheat','Before each call \u00b7 full spec loaded'],['Caching','Prompt caching \u00b7 ~45k tokens cached'],['Tokens last call','6,204']],
    note:'Never in async path. Prompt caching keeps ~45k spec tokens warm across calls. Claude Haiku handles post-call extraction to keep cost down.' },
  kokoro:  { role:'Inworld TTS Mini \u00b7 Cloud API', status:'READY', sc:'#9f00fa',
    m:[['Provider','Inworld TTS 1.5 Max \u00b7 Cloud API'],['Protocol','WebSocket streaming'],['First chunk','~200ms (Google SJC, 13ms)'],['Quality','ELO 1577 \u00b7 Native format'],['Pre-render','First turn + VM + 2 responses cached before dial'],['Fallback','Kokoro v1 on GPU (if Inworld health check fails)']],
    note:'Primary TTS: Inworld TTS Mini via cloud WebSocket API. ELO 1577 quality. Kokoro v1 on GPU worker as silent fallback only \u2014 activates if Inworld health check fails at boot.' },
  spaces:  { role:'DO Spaces \u00b7 Call Recordings', status:'READY', sc:'#60be35',
    m:[['Type','S3-compatible bucket'],['Format','Dual-channel stereo (client left, Sales right)'],['Streaming','Worker \u2192 sales-app \u2192 Spaces (real-time)'],['Cost','~$5/mo at launch volume'],['Retention','Configurable in Controller (default: keep all)']],
    note:'Recording survives worker death \u2014 audio streams to sales-app in real-time via WebSocket, then to DO Spaces. Post-call: stitched into stereo recording.' },
  haiku:   { role:'Claude Haiku 4.5 \u00b7 Async Extraction', status:'STANDBY', sc:'#b0b0b0',
    m:[['Model','claude-haiku-4-5-20251001'],['Host','Anthropic API (cloud)'],['Usage','Post-call only \u00b7 NEVER live path'],['Tasks','Sentiment \u00b7 Intent \u00b7 HubSpot notes'],['Cost','Fraction of Sonnet']],
    note:'Async extraction after the call. Keeps Sonnet reserved exclusively for the live voice path.' },
  telnyx:  { role:'Telnyx \u00b7 Voice + SMS', status:'OK', sc:'#60be35',
    m:[['Number','\u26a0 TBD \u2014 pre-launch blocker'],['SIP trunk','Outbound PSTN dial'],['Cost','$0.007/min + $0.02/SMS'],['SMS touches','Day 8 \u00b7 Day 18 \u00b7 Day 30'],['Transfer','Parallel ring up to 3 reps \u00b7 16s timeout'],['Call control','Sales Worker owns all Telnyx legs during live calls']],
    note:'Why Telnyx over Twilio: lower cost/min, better SIP flexibility. See ZC_DECISIONS.md. Sales Worker controls all Telnyx call legs directly \u2014 including parallel ring for warm transfer.' },
  client:  { role:'Client \u00b7 Property Manager', status:'TARGETING', sc:'#ff4040',
    m:[['Current target','Michelle Forkas \u00b7 Summit Mgmt Mgmt'],['propID','#7856 \u00b7 $127,400 \u00b7 28d stale'],['Script','T2-A (7\u201330d staleness)'],['Call window','Tue\u2013Fri \u00b7 10:30\u20134:30 PM PT'],['Channels','Voice \u00b7 SMS \u00b7 Email']],
    note:'Sales AI always leads with proposal number AND property name. No generic openers ever.' },
  reps:    { role:'Transfer Pool \u00b7 10 Reps', status:'7 AVAILABLE', sc:'#60be35',
    m:[['Priority 1','Marco Diaz \u00b7 (555) 488-4422'],['Priority 2','Sarah Mitchell \u00b7 (555) 755-9125'],['Default weight','Equal across all reps (Alex adjusts in Controller)'],['Ring logic','Up to 3 simultaneous \u00b7 16s timeout'],['On call','0 active'],['Blockers','OQ-1 Dan phone \u00b7 OQ-2 Jennifer phone \u00b7 OQ-5 shared phone \u00b7 OQ-6 Leah no HS seat']],
    note:'Transfer SMS fires to the rep immediately when ringing starts \u2014 before anyone picks up. Rep matching by hs_owner_id, NOT by email (3 confirmed mismatches).' },
};
